apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: sso75-https-external-db-xsite
    application: sso
    rh-sso: rh-sso-7.5-v0.1-terna
    template: sso75-https-external-db-xsite
  name: sso75-oracle-bc
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: sso-terna:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: openshift/rhsso-postgresql/build
    git:
      uri: git@github.com:fceresol/rhsso-xsite-ext-db.git
    sourceSecret:
      name: sshkey-sso
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: sso75-openshift-rhel8:7.5
        namespace: openshift
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers: []

